// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Dev only: `migrate dev` replays migrations into a throwaway database
    // to detect drift. Without this it tries to use the main one and fails.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
